# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Users/wen02/Documents/GitHub/zynq_tdc/src/ports.xdc

# XDC: F:/Users/wen02/Documents/GitHub/zynq_tdc/src/timing.xdc

# Block Designs: bd/TDCsystem/TDCsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem || ORIG_REF_NAME==TDCsystem} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/TDCsystem_AXITDC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_AXITDC_0_0 || ORIG_REF_NAME==TDCsystem_AXITDC_0_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_AXITDC_1_0/TDCsystem_AXITDC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_AXITDC_1_0 || ORIG_REF_NAME==TDCsystem_AXITDC_1_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_clk_wiz_0_0/TDCsystem_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_clk_wiz_0_0 || ORIG_REF_NAME==TDCsystem_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_processing_system7_0_0/TDCsystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_processing_system7_0_0 || ORIG_REF_NAME==TDCsystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_ps7_0_axi_periph_0/TDCsystem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==TDCsystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_rst_ps7_0_100M_0/TDCsystem_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==TDCsystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_xlconstant_0_0/TDCsystem_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_xlconstant_0_0 || ORIG_REF_NAME==TDCsystem_xlconstant_0_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_xbar_0/TDCsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_xbar_0 || ORIG_REF_NAME==TDCsystem_xbar_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_auto_pc_1/TDCsystem_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_auto_pc_1 || ORIG_REF_NAME==TDCsystem_auto_pc_1} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_auto_pc_0/TDCsystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_auto_pc_0 || ORIG_REF_NAME==TDCsystem_auto_pc_0} -quiet] -quiet

# IP: bd/TDCsystem/ip/TDCsystem_auto_pc_2/TDCsystem_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDCsystem_auto_pc_2 || ORIG_REF_NAME==TDCsystem_auto_pc_2} -quiet] -quiet

# XDC: bd/TDCsystem/TDCsystem_ooc.xdc
