# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_auto_pc_2/TDCsystem_auto_pc_2.xci
# IP: The module: 'TDCsystem_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_auto_pc_2/TDCsystem_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TDCsystem_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_auto_pc_2/TDCsystem_auto_pc_2.xci
# IP: The module: 'TDCsystem_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_auto_pc_2/TDCsystem_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TDCsystem_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
