# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/TDCsystem_AXITDC_0_0.xci
# IP: The module: 'TDCsystem_AXITDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/TDCsystem_AXITDC_0_0.xci
# IP: The module: 'TDCsystem_AXITDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: f:/Users/wen02/Documents/GitHub/zynq_tdc/TDCsystem/TDCsystem.srcs/sources_1/bd/TDCsystem/ip/TDCsystem_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
