set_property SRC_FILE_INFO {cfile:F:/Users/wen02/Documents/GitHub/zynq_tdc/src/ports.xdc rfile:../../../../src/ports.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:F:/Users/wen02/Documents/GitHub/zynq_tdc/src/timing.xdc rfile:../../../../src/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports hit0]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports hit1]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports LEDout[0]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports LEDout[1]]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks clk_fpga_0]
